#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish containers and run deployments.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else

    # Publish containers
    "${DIR}/cipublish"

    docker-compose -f docker-compose.ci.yml build terraform

    # Run deployments
    IMAGE_VERSION="${TRAVIS_COMMIT}" docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra plan
    IMAGE_VERSION="${TRAVIS_COMMIT}" docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra apply


    fi
    exit
fi
