#!/bin/bash
set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")"
ANSIBLE_DIR="${DIR}/../deployment/ansible"
BRANCH="${TRAVIS_BRANCH:-develop}"

if [ "${TRAVIS_BRANCH}" = "master" ]; then
  ANSIBLE_INVENTORY_FILE="production"
  export ANSIBLE_INVENTORY_FILE
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish containers and run deployments.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else

    # Publish containers
    "${DIR}/cipublish"

    docker-compose -f docker-compose.ci.yml build terraform

    # Run deployments
    docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra plan
    docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra apply


    fi
    exit
fi
